# Local development configuration for the go-notification-service

project_id: "gemini-power-test"
listen_addr: ":8086"

cors:
  allowed_origins:
    - "http://localhost:3000" # Common for React
    - "http://localhost:4200" # Common for Angular
    - "http://localhost:5173" # Common for Vite
    - "http://localhost:8080" # Common for general dev servers

subscription_id: "push-notifications-sub"
subscription_dlq_topic_id: "push-notifications-dlq"

num_pipeline_workers: 5