gcloud run deploy notification-service \
  --source . \
  --project gemini-power-test \
  --region europe-west1 \
  --allow-unauthenticated \
  --set-env-vars="GCP_PROJECT_ID=gemini-power-test" \
  --set-env-vars="IDENTITY_SERVICE_URL=https://node-identity-service-885150127230.europe-west1.run.app" \
  --set-env-vars="GOOGLE_APPLICATION_CREDENTIALS=/secrets/service-account.json" \
  --set-env-vars="LOG_LEVEL=info" \
  --set-env-vars="CORS_ALLOWED_ORIGINS=https://messenger-app-885150127230.europe-west1.run.app" \
  --set-secrets="/secrets/service-account.json=fcm-service-account:latest"